### PR TITLE
Fix landing-page footer links

### LINKED ISSUE #308: Update links in footer
Update the links in landing page's footer: (Parity technologies, Terms & conditions, Privacy policy, Report an issue)

### PR DESCRIPTION
**Pull request by raoulmillais**
- Fixes #308

### CODE REVIEW

File: projects/landing-page/src/App.tsx [hunk 1]
```diff
@@ -155,9 +155,9 @@ const App: React.FunctionComponent = () => {
               {/* TODO: Playground */}
               <Box>
                 <FooterLink>© 2021 Parity Technologies</FooterLink>
```
Comment (wirednkod) [inline projects/landing-page/src/App.tsx:157]: Add a link to "https://www.parity.io/"

**Review by wirednkod — CHANGES_REQUESTED** [review]

File: projects/landing-page/src/App.tsx (hunk 1 above)
Comment (raoulmillais) [reply projects/landing-page/src/App.tsx]: Fixed

**Review by wirednkod — APPROVED** [review]
