### PR TITLE
Apply name and email in deploy script

### LINKED ISSUE #1108: Bug during CI deploy of projects
During deploy script there is an error:
```
fatal: empty ident name (for <runner@fv-az243-292.eyhnzsvkqwvufobmc3lzdbadce.jx.internal.cloudapp.net>) not allowed
```
that does not allow deploy to complete successfully

### PR DESCRIPTION
**Pull request by wirednkod**
fixes #1108

### CODE REVIEW

**Review by tomaka — APPROVED** [review]

File: deploy.sh [hunk 1]
```diff
@@ -47,12 +47,13 @@ echo -e "\033[0;32mRebuilding everything...\033[0m"
 yarn build
 
 echo -e "\033[0;32mGenerating site...\033[0m"
+
```
Comment (tomaka) [inline deploy.sh:50]:
```suggestion
```
